config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :boards
  get '/payments/success', to: 'payments#success'
  get '/payments/cancel', to: 'pages#index'
  root 'pages#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
# frozen_string_literal: true

class Board < ApplicationRecord
  validates :title, presence: true
  validates :condition, presence: true
  validates :description, presence: true, length: { minimum: 10 }
  validates :price, presence: true
  belongs_to :user
  has_one_attached :picture

  def price_in_cents
    (price * 100).to_i
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable
  has_many :boards, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :find_board, only: %i[show edit update destroy]
  def index
    @boards = Board.all
  end

  def show
    @board = Board.find_by(id: params[:id])
    if current_user
    session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      mode: 'payment',
      line_items: [{
        price_data: {
          product_data: {
            name: @board.title,
            description: @board.description
          },
          currency: 'aud',
          unit_amount: @board.price_in_cents
        },
        quantity: 1
      }],
      payment_intent_data: {
        metadata: {
          board_id: @board.id,
          user_id: current_user.id
        }
      },
      success_url: URI.join(root_url, payments_success_path),
      cancel_url: URI.join(root_url, payments_cancel_path)
    )
    @session_id = session.id
  end
  end

  def new
    @board = Board.new
  end

  def create
    @board = current_user.boards.new(boards_params)
    if @board.save
      redirect_to @board
    else
      render :new
    end
  end

  def edit; end

  def update
    if @board.update(boards_params)
      redirect_to @board
    else
      render :edit
    end
  end

  def destroy
    @board.destroy
    redirect_to root_path
  end

  private

  def boards_params
    params.require(:board).permit(:title, :condition, :description, :price, :picture)
  end

  def find_board
    @board = Board.find(params[:id])
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def index; end
end

app/controllers/payments_controller.rb
# frozen_string_literal: true

class PaymentsController < ApplicationController
  def success; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/payments_helper.rb
# frozen_string_literal: true

module PaymentsHelper
end

app/helpers/store_helper.rb
# frozen_string_literal: true

module StoreHelper
end

app/views/boards/edit.html.erb
<%= @board.title%>
<%= render 'shared/form' %>

app/views/boards/index.html.erb
<div class="storefront">
    <h1 class="title"> Board Shop </h1>
        <div class="card-columns">
            <% @boards.each do |board| %>
                <div class="card">
                    <div class="card-block">
                        <%= image_tag(board.picture, class: 'image')if board.picture.attached? %> 
                        <h5 class="card-title"> <%= board.title%> </h5>
                        <p class="card-subtitle mb-2 text-muted"> <%= board.condition%> </p>
                        <h5 class="card-text mt-2"> <%= board.price%> </h5>
                        <div class="button">
                            <%= link_to "View", board_path(board), class: "btn btn-primary" %>
                        </div>
                    </div>
                </div>
            <%end%>
        </div>
</div>
    

app/views/boards/new.html.erb
<div class="listing-title">
    <h1> New Lisiting </h1>
</div>
<%= render 'shared/form' %>

app/views/boards/show.html.erb
<div class="card-columns">
    <div class="card">
        <%= image_tag(@board.picture, class: 'image') %>
        <div class="card-block">
            <h3> <%= @board.title %> </h3>
            <h3>Condtion: <%= @board.condition %> </h3>
            <h3>Description: <%= @board.description %> </h3>
            <h3>Price: <%= @board.price %> </h3>
            <% if current_user%>
            <button data-stripe="payment">Buy<%= @board.price%> </button>
            <%else%>
            <h4> Sign in to purchase </h4>
            <%end%>
            <script src="https://js.stripe.com/v3/"></script>
            <script>
                document.querySelector("[data-stripe='payment']").addEventListener("click", () => {
                const stripe = Stripe("<%= Rails.application.credentials.dig(:stripe, :public_key) %>");
                stripe.redirectToCheckout({
                    sessionId: "<%= @session_id %>"
                    });
                });
            </script>
            <% if user_signed_in? && current_user.id == @board.user.id %>
            <%= link_to "Edit", edit_board_path(@board) %>
            <%= link_to "Delete", board_path(@board), method: :delete %>
            <% end %>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  
  <!-- Google font -->
  <link href="https://fonts.googleapis.com/css2?family=Luckiest+Guy&display=swap" rel="stylesheet">
  
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<div class="hero_image">
    <h1>Hang Ten Boards</h1>
</div>

app/views/payments/cancel.html.erb
Payment cancelled
<%= link-to "Go to Board Shop", board_path%>

app/views/payments/success.html.erb
You've successfully made a payment
<%= link_to "Go to Board Shop", boards_path%>

app/views/shared/_form.html.erb
<%= form_with model: @board do |form| %>
<div class="form">
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :condition %><br>
    <%= form.text_area :condition %>
  </div>
  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </div>
  <div>
    <%= form.label :price %><br>
    <%= form.text_area :price %>
  </div>
   <div>
    <%= form.label :picture %><br>
    <%= form.file_field :picture, accept: 'image/png, image/jpg, image/jpeg' %>
  </div>
  <br>
  <div>
    <%= form.submit %>
  </div>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<nav>
    <ul>
        <% if user_signed_in? %>
        <li> <%= button_to "Sign Out", destroy_user_session_path, method: "delete", class: 'nav-text' %> </li>
        <li><%= link_to "Board Shop", "/boards", class: 'nav-text' %> </li>
        <li><%= link_to "New Listing", "/boards/new", class: 'nav-text' %> </li>
        <% else %>
        <li><%= link_to "Sign In", new_user_session_path, class: 'nav-text' %> </li>
        <li><%= link_to "Board Shop", "/boards", class: 'nav-text' %> </li>
        <li><%= link_to "New Listing", "/boards/new", class: 'nav-text' %> </li>
   </ul>
<%end%>
</nav>